### ISSUE TITLE
Malware?

### ISSUE THREAD

**Issue by XyzKangUI** [Ascension-Addons/OmniBar#1]
### Description

It seems as if the addon is secretly whispering every RunScript to "libraries". This is to be considered spyware. Given that "Jammin" has backported the addon, it's reasonable to assert that this individual has surreptitiously inserted this code.

https://github.com/Ascension-Addons/OmniBar/blob/a1f4aa7d0d82c2cba9c889674aa4a8e1cb75fc1f/OmniBar/OmniBar.lua#L885

Solution:

This piece of intrusive code should be deleted

**Comment by andrew6180** [comment]
This has no effect on Ascension other than the very minor impact hooking runscript has since we don't have a blackrock or icecrown realm. 

If this backport is still used on warmane it would be good to report your findings there.
